# Generated by Django 3.1.2 on 2020-11-07 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_shop_ref', '0008_auto_20201107_2356'),
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='year_of_publishing',
        ),
        migrations.AddField(
            model_name='book',
            name='year_of_publishing',
            field=models.ManyToManyField(to='book_shop_ref.YearPublishing', verbose_name='Год издания'),
        ),
    ]
