# Generated by Django 3.1.2 on 2020-11-07 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_shop_ref', '0008_auto_20201107_2356'),
        ('book', '0002_auto_20201107_2356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='book_format',
        ),
        migrations.AddField(
            model_name='book',
            name='book_format',
            field=models.ManyToManyField(to='book_shop_ref.Format', verbose_name='Формат книги'),
        ),
    ]
