# Generated by Django 3.1.2 on 2020-11-07 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_shop_ref', '0013_auto_20201108_0140'),
        ('book', '0004_book_isbn'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='age',
            field=models.ForeignKey(default='5', on_delete=django.db.models.deletion.PROTECT, related_name='books', to='book_shop_ref.age', verbose_name='Возрастные ограничения'),
        ),
        migrations.AddField(
            model_name='book',
            name='type_binding',
            field=models.ManyToManyField(to='book_shop_ref.Binding', verbose_name='Тип переплёта'),
        ),
    ]
