# Generated by Django 3.1.2 on 2020-11-08 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_shop_ref', '0014_remove_publishinghouse_city'),
        ('book', '0005_auto_20201108_0142'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='city',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='publishing_houses', to='book_shop_ref.city', verbose_name='Город'),
        ),
    ]
