# Generated by Django 3.1.2 on 2020-11-08 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_shop_ref', '0015_auto_20201108_1201'),
        ('book', '0006_book_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='city',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='publishing_houses', to='book_shop_ref.city', verbose_name='Город'),
        ),
    ]
