# Generated by Django 3.1.2 on 2020-11-08 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_auto_20201108_1201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='city',
        ),
    ]
