# Generated by Django 3.1.2 on 2020-11-08 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_shop_ref', '0016_delete_city'),
        ('book', '0009_auto_20201108_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='series',
            field=models.ForeignKey(blank=True, default=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='books', to='book_shop_ref.series', verbose_name='Название серии'),
        ),
    ]
