# Generated by Django 3.1.2 on 2020-11-08 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_shop_ref', '0016_delete_city'),
        ('book', '0010_auto_20201108_1230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='genres',
        ),
        migrations.AddField(
            model_name='book',
            name='genres',
            field=models.ManyToManyField(to='book_shop_ref.Genres', verbose_name='Жанр'),
        ),
    ]
