# Generated by Django 3.1.3 on 2020-11-08 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_shop_ref', '0018_binding'),
        ('book', '0012_auto_20201108_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='type_binding',
            field=models.ManyToManyField(to='book_shop_ref.Binding', verbose_name='Тип переплёта'),
        ),
    ]
