# Generated by Django 3.1.2 on 2020-11-01 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_shop_ref', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Название книги')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('stock', models.PositiveIntegerField(verbose_name='Количество в наличии')),
                ('available', models.BooleanField(default=True, verbose_name='Доступно к заказу')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата внесения')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('num_of_pages', models.PositiveIntegerField(verbose_name='Количество страниц')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='book_shop_ref.author', verbose_name='Автор')),
                ('genres', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='book_shop_ref.genres', verbose_name='Жанр')),
                ('publishing_house', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='book_shop_ref.publishinghouse', verbose_name='Издательство')),
                ('series', models.ForeignKey(default=True, on_delete=django.db.models.deletion.PROTECT, to='book_shop_ref.series', verbose_name='Название серии')),
            ],
        ),
    ]
