# Generated by Django 3.1.2 on 2020-11-06 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_shop_ref', '0003_auto_20201102_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genres',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='books', to='book_shop_ref.genres', verbose_name='Жанр'),
        ),
        migrations.AlterField(
            model_name='book',
            name='series',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.PROTECT, related_name='books', to='book_shop_ref.series', verbose_name='Название серии'),
        ),
    ]
