# Generated by Django 3.1.2 on 2020-11-06 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_shop_ref', '0004_auto_20201106_1957'),
    ]

    operations = [
        migrations.CreateModel(
            name='Format',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=10, verbose_name='Формат книги')),
            ],
        ),
        migrations.CreateModel(
            name='YearPublishing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4, verbose_name='Год издания')),
            ],
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
