# Generated by Django 3.1.2 on 2020-11-07 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_shop_ref', '0008_auto_20201107_2356'),
    ]

    operations = [
        migrations.CreateModel(
            name='Isbn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(default='', max_length=15, unique=True, verbose_name='ISBN')),
            ],
        ),
        migrations.AlterField(
            model_name='format',
            name='size',
            field=models.CharField(choices=[('1', '84×108/32'), ('2', '60×90/16'), ('3', '60×90/32'), ('4', '70×108/32'), ('5', '70×90/32'), ('6', '75×90/16'), ('7', '70×90/16'), ('8', '70×90/8'), ('9', '84×108/16'), ('10', '70×100/64')], default='1', max_length=10, verbose_name='Формат книги'),
        ),
    ]
