# Generated by Django 3.1.2 on 2020-11-07 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_shop_ref', '0011_delete_isbn'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgeRestrictions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_restrictions', models.CharField(choices=[('1', '0+'), ('2', '6+'), ('3', '12+'), ('4', '16+'), ('5', '18+')], default='5', max_length=3, verbose_name='Возрастные ограничения')),
            ],
        ),
    ]
