# Generated by Django 3.1.2 on 2020-11-07 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_shop_ref', '0012_agerestrictions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AgeRestrictions',
            new_name='Age',
        ),
        migrations.RenameField(
            model_name='age',
            old_name='age_restrictions',
            new_name='age',
        ),
    ]
