# Generated by Django 3.1.2 on 2020-11-08 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_shop_ref', '0014_remove_publishinghouse_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(default='', max_length=50, verbose_name='Город'),
        ),
    ]
