# Generated by Django 3.1.2 on 2020-11-08 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_remove_book_city'),
        ('book_shop_ref', '0015_auto_20201108_1201'),
    ]

    operations = [
        migrations.DeleteModel(
            name='City',
        ),
    ]
