# Generated by Django 3.1.3 on 2020-11-08 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0012_auto_20201108_1826'),
        ('book_shop_ref', '0016_delete_city'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Age',
        ),
        migrations.DeleteModel(
            name='Binding',
        ),
    ]
