# Generated by Django 3.1.3 on 2020-11-08 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_shop_ref', '0017_auto_20201108_1826'),
    ]

    operations = [
        migrations.CreateModel(
            name='Binding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_binding', models.CharField(choices=[('1', '7БЦ'), ('2', '7Б'), ('3', '7Т'), ('4', 'КБС'), ('5', 'ШКС'), ('6', 'Брошюровка на пружину'), ('7', 'Брошюровка скобой'), ('8', 'Интегральный'), ('9', 'Болты')], default='1', max_length=30, verbose_name='Тип переплёта')),
            ],
        ),
    ]
